create table if not exists public.contact_messages (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    first_name text,
    last_name text,
    email text not null,
    message text not null,
    source text default 'sacreationweb.com'
);

alter table public.contact_messages enable row level security;

do $$
begin
    create policy "Allow server contact inserts"
    on public.contact_messages
    for insert
    to service_role
    with check (true);
exception
    when duplicate_object then null;
end $$;
