const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../../assets/kirby-site-contract'),R=require('../../assets/kirby-site-renderer'),F=require('../fixtures/kirby-site.cjs');
function catalog(){const s=F.site();s.catalog={categories:[{id:'category',name:'Collection',parentId:null}],products:[{id:'product',name:'Pièce',description:'',categoryIds:['category'],attributes:[],assetIds:[],deliveryInfo:null,demonstration:false,sources:[{field:'offers',quote:'149 €, soldé à 109 €, tailles 36 à 42'}],target:F.target('details'),offers:[{id:'offer',sku:null,options:[{name:'Taille',values:['36','38','40','42']}],saleUnit:'unit',unitsPerLot:null,price:14900,salePrice:10900,currency:'EUR',stockQuantity:null,availability:'unknown',assetIds:[]}]}]};s.pages[0].sections[0].blocks=[{id:'products',type:'products',title:'',text:'',assetId:'',items:[],chartType:'bar',illustrative:false,productIds:['product']}];s.pages[0].sections[0].slots.artifactBlockIds=['products'];return s;}
test('catalogue price edits preserve original price, pages, variants and visual identity',()=>{const s=catalog();C.validate(s);const p=C.clone(s.catalog.products[0]);p.offers[0].salePrice=11920;const next=C.apply(s,F.decision([{type:'put_product',product:p}]));assert.equal(next.catalog.products[0].offers[0].price,14900);assert.equal(next.catalog.products[0].offers[0].salePrice,11920);assert.deepEqual(next.pages,s.pages);assert.deepEqual(next.design,s.design);assert.equal(s.catalog.products[0].offers[0].salePrice,10900);});
test('invalid sale, missing product, category cycle and fictitious per-variant inventory reject atomically',()=>{for(const change of [s=>s.catalog.products[0].offers[0].price=null,s=>s.catalog.products[0].offers[0].salePrice=15000,s=>s.catalog.categories[0].parentId='category',s=>s.catalog.products[0].offers[0].stockQuantity=4,s=>s.catalog.products=[]]){const s=catalog();change(s);assert.throws(()=>C.validate(s));}});
test('legacy site remains unchanged and catalogue colour edit preserves every commerce field',()=>{const old=F.site();const before=JSON.stringify(old);C.validate(old);assert.equal(JSON.stringify(old),before);const s=catalog();const next=C.apply(s,F.decision([{type:'set_design',design:{...s.design,accent:'#223344'}}]));assert.deepEqual(next.catalog,s.catalog);});
test('product renderer exposes selectable variants and distinct original/sale prices without purchase simulation',()=>{const s=catalog();s.catalog.products[0].target=F.target('home');const html=R.render(s,'home','p');assert.match(html,/data-product-option="Taille"/);assert.match(html,/<del[^>]*>149/);assert.match(html,/<strong>109/);assert.match(html,/Soldé/);assert.doesNotMatch(html,/Ajouter au panier|Paiement|en stock/);});
test('lots retain lot price and unknown inventory',()=>{const s=catalog(),o=s.catalog.products[0].offers[0];o.saleUnit='lot';o.unitsPerLot=6;o.price=6000;o.salePrice=null;C.validate(s);assert.match(R.render(s,'home','p'),/le lot de 6/);assert.equal(o.stockQuantity,null);});
test('sale collection is computed from offers and updates without rewriting the page',()=>{const s=catalog(),b=s.pages[0].sections[0].blocks[0];b.productIds=[];b.onSaleOnly=true;b.categoryId=null;assert.match(R.render(s,'home','p'),/data-product-id="product"/);const p=C.clone(s.catalog.products[0]);p.offers[0].salePrice=null;const next=C.apply(s,F.decision([{type:'put_product',product:p}]));assert.deepEqual(next.pages,s.pages);assert.doesNotMatch(R.render(next,'home','p'),/data-product-id="product"/);});

test('catalogue cards contain one price group and reserve variants and prose for product details',()=>{const s=catalog();s.catalog.products[0].description='Description réservée à la fiche';const html=R.render(s,'home','p');assert.equal((html.match(/class="ks-product-price"/g)||[]).length,1);assert.doesNotMatch(html,/data-product-option|ks-product-options|Description réservée|data-product-availability|Contacter \/ commander/);assert.match(html,/ks-product-link/);s.catalog.products[0].target=F.target('home');const detail=R.render(s,'home','p');assert.match(detail,/data-product-option="Taille"/);assert.match(detail,/Description réservée/);});
test('lot quantity never creates unit calculations or sale styling',()=>{const s=catalog(),o=s.catalog.products[0].offers[0];o.saleUnit='lot';o.unitsPerLot=6;o.price=27000;o.salePrice=null;const html=R.render(s,'home','p');assert.match(html,/270/);assert.match(html,/le lot de 6/);assert.doesNotMatch(html,/<del|Soldé|45[,.]|÷|Calcul|Indisponible/);});

test('stage renders commerce once outside the decorative scene without changing saved data',()=>{const s=catalog();s.pages[0].sections[0].composition='product-stage';const before=JSON.stringify(s),html=R.render(s,'home','p');assert.match(html,/ks-placement-catalogue/);assert.doesNotMatch(html,/ks-placement-scene/);assert.equal((html.match(/data-product-id="product"/g)||[]).length,1);assert.equal(JSON.stringify(s),before);});
